### PR TITLE
Use ES2020 on tsconfig

### PR DESCRIPTION
**Pull request by hamidrezahanafi**
This new module is building for ES2022 and need transforming on older repos.
Change back the build to es5 and commonjs

### CODE REVIEW

**Comment by hamidrezahanafi** [comment]
@VaguelySerious Do you have any objection on merging this?

**Comment by VaguelySerious** [comment]
@hamidrezahanafi The reason `react-quill-new` builds to ESM is because `quill@^2.0.0` builds to ESM. I'm not going to superseed their decision in moving to native quill modules, as `react-quill-new` is meant to be a lightweight wrapper around Quill.
If there is a good argument as to why `quill`'s reasons for moving to ESM shouldn't apply to `react-quill-new`, I'd be open to reconsider. That said, I don't know the reasons for `quill`s decision to move to ESM. I suspect it is due to bundling and tree shaking concerns, but if you're invested, please feel free to look into it an present an argument.

**Comment by VaguelySerious** [comment]
@hamidrezahanafi Fair concern. I'll change it to `ES2020`. For people with specific browser targets, I assume they'll use babel with `preset-env` in their bundler and transform dependencies on production builds.

**Comment by hamidrezahanafi** [comment]
Thanks @VaguelySerious , Updated PR to ES2020

**Comment by VaguelySerious** [comment]
Published as `3.2.2`

**Pull request merged**
